# src/config.py

OUTLOOK_DOMAIN = "autonomadeica.edu.pe"

CAMPUS_MAP = {
    "SEDE CHINCHA ALTA": "SEDE CENTRAL",
    "FILIAL ICA": "FILIAL - ICA",
    "FILIAL CHINCHA - H": "FILIAL HUAURA",
    "SEDE SUNAMPE": "SUNAMPE",
}

# ✅ Virtual si PENSIÓN ESCALA contiene "VIR"
def es_virtual_por_pension(pension_escala: str) -> bool:
    if pension_escala is None:
        return False
    return "VIR" in str(pension_escala).upper()

# Modalidad Matrícula -> TipoDeAdmission_RelationId (test válido)
TIPO_ADMISION_MAP = {
    "GENERAL - PRIMEROS PUESTOS": 2,
    "ENFER. Y ARQUITC. - PRIMERA OPCION (PROMOCIONAL)": 3,
    "GENERAL - PRIMERA OPCION": 3,
    "GENERAL - PRIMERA OPCION (PROMOCIONAL)": 3,
    "GENERAL - MODALIDAD ORDINARIO (PROMOCIONAL)": "test",
    "ENFER. Y ARQUITC. - MODALIDAD ORDINARIA": "test",
    "MEDICINA HUMANA - MODALIDAD ORDINARIA P (PROMOCIONAL)": "test",
    "MEDICINA HUMANA - MODALIDAD ORDINARIA E (PROMOCIONAL)": "test",
    "MEDICINA HUMANA - MODALIDAD ORDINARIA E": "test",
    "MEDICINA HUMANA - TRASLADO EXTERNO (PROMOCIONAL)": 7,
    "GENERAL - MODALIDAD ORDINARIA": "test",
    "A DISTANCIA - GENERAL - ORDINARIO": "test",
    "A DISTANCIA - GENERAL - ORDINARIO - PROM": "test",
    "MEDICINA HUMANA - PRIMERA OPCIÓN E (PROMOCIONAL)": 3,
    "ENFER. Y ARQUITC. - MODALIDAD ORDINARIA (PROMOCIONAL)": "test",
    "MEDICINA HUMANA - PRIMERA OPCIÓN P (PROMOCIONAL)": 3,
    "MEDICINA HUMANA - PRIMERA OPCIÓN E": 3,
    "ENFER. Y ARQUITC. - PRIMERA OPCIÓN": 3,
    "ENFER. Y ARQUITC. - EGRESADOS, GRADUADOS O TITULADOS": 4,
    "ENFER. Y ARQUITC. - EGRESADOS, GRADUADOS O TITULADOS (PROM)": 4,
    "GENERAL - EGRESADOS, GRADUADOS O TITULADOS (PROMOCIONAL)": 4,
    "GENERAL - EGRESADOS, GRADUADOS O TITULADOS": 4,
    "MEDICINA HUMANA - EGRESADOS, GRADUADOS Y TITULADOS (PROM)": 4,
    "ENFER. Y ARQUITC. - TERCIO SUPERIOR": 1,
    "GENERAL - TERCIO SUPERIOR": 1,
    "MEDICINA HUMANA - TERCIO SUPERIOR": 1,
    "MEDICINA HUMANA - PROGRAMA BECA 18": 6,
    "GENERAL - BECA 18": 6,
    "GENERAL - TRASLADO EXTERNO (PROMOCIONAL)": 7,
    "ENFER. Y ARQUITC. - TRASLADO EXTERNO (PROMOCIONAL)": 7,
    "GENERAL - DEPORTISTAS DESTACADOS O ALTA COMPETENCIA": 10,
    "GENERAL - TRASLADO ULD (PROMOCIONAL)": 5,
    "GENERAL - TRASLADO ULD": 5,
    "ENFER. Y ARQUITC. - PRIMEROS PUESTOS": 2,
    "MEDICINA HUMANA - PRIMEROS PUESTOS": 2,
    "GENERAL - MODALIDAD REGULAR": "test",
    "MODALIDAD ORDINARIA (EXON. DER. POST)": "test",
    "MODALIDAD EXTEMPORÁNEO": "test",
    "MODALIDAD ORDINARIA (PROMOCIÓN 50% Y 30%)": "test",
    "MODALIDAD ORDINARIO REGULAR": "test",
    "TRASLADO UNIVER. LICENCIA DENEGADA": 5,
    "GENERAL - TRASLADOS EXTERNOS": 7,
}

def estado_estudiante_key(ciclo: int) -> int:
    return 1 if ciclo == 1 else 2

# ✅ TABLA MAESTRA OFICIAL (tu cuadro)
# Clave: PROGRAMA ACADÉMICO normalizado (sin tildes/upper lo haremos en core) + flag virtual
# Valor: (ProgramaAcadémico_Codigo, PlanCurricular_RelationId)
PROGRAMA_MASTER = [
    ("ADMINISTRACIÓN DE EMPRESAS", False, "P38", "P38-20242"),
    ("ENFERMERÍA", False, "P02", "P02-20242"),
    ("PSICOLOGÍA", False, "P04", "P04-20242"),
    ("OBSTETRICIA", False, "P09", "P09-20242"),
    ("INGENIERÍA CIVIL", False, "P32", "P32-20242"),
    ("MEDICINA HUMANA", False, "P31", "P31-20251"),
    ("INGENIERÍA INDUSTRIAL", False, "P06", "P06-20242"),
    ("DERECHO", False, "P08", "P08-20242"),
    ("TECNOLOGÍA MÉDICA - OPTOMETRÍA", False, "P55", "P55-20251"),
    ("TECNOLOGÍA MÉDICA - TERAPIA DE LENGUAJE", False, "P37", "P37-20251"),
    ("TECNOLOGÍA MÉDICA - TERAPIA FÍSICA Y REHABILITACIÓN", False, "P36", "P36-20251"),
    ("INGENIERÍA DE SISTEMAS", False, "P03", "P03-20242"),
    ("ARQUITECTURA", False, "P34", "P34-20251"),
    ("CONTABILIDAD", False, "P07", "P07-20242"),
    ("TECNOLOGÍA MÉDICA - LABORATORIO CLÍNICO Y ANATOMIA PATOLOGICA", False, "P35", "P35-20251"),
    ("ADMINISTRACIÓN Y FINANZAS", False, "P01", "P01-20242"),
    ("INGENIERÍA EN INDUSTRIAS ALIMENTARIAS", False, "P05", "P05-20201"),

    # Virtuales
    ("ADMINISTRACIÓN DE EMPRESAS - VIRTUAL", True, "P38V", "P38V-20251"),
    ("DERECHO - VIRTUAL", True, "P08V", "P08V-20251"),
    ("CONTABILIDAD - VIRTUAL", True, "P07V", "P07V-20251"),
]